// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLW1L4PEV4K_72mDZ8ziTMomuaw0jVi_o',
    appId: '1:977548969242:web:e8304a2b4fc729ea3458a3',
    messagingSenderId: '977548969242',
    projectId: 'prakflutterfirebase-63b02',
    authDomain: 'prakflutterfirebase-63b02.firebaseapp.com',
    storageBucket: 'prakflutterfirebase-63b02.appspot.com',
    measurementId: 'G-QQKS8F2JQN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnpxpAbCs49oB30XjYyMEVrGr4ucyXEho',
    appId: '1:977548969242:android:741297528957ec3b3458a3',
    messagingSenderId: '977548969242',
    projectId: 'prakflutterfirebase-63b02',
    storageBucket: 'prakflutterfirebase-63b02.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRq6nkeNhnF8bgrJ54i0wao42BNXhCcwg',
    appId: '1:977548969242:ios:c0db011d4c4e16503458a3',
    messagingSenderId: '977548969242',
    projectId: 'prakflutterfirebase-63b02',
    storageBucket: 'prakflutterfirebase-63b02.appspot.com',
    iosBundleId: 'com.example.firebaseAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRq6nkeNhnF8bgrJ54i0wao42BNXhCcwg',
    appId: '1:977548969242:ios:c0db011d4c4e16503458a3',
    messagingSenderId: '977548969242',
    projectId: 'prakflutterfirebase-63b02',
    storageBucket: 'prakflutterfirebase-63b02.appspot.com',
    iosBundleId: 'com.example.firebaseAuth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLW1L4PEV4K_72mDZ8ziTMomuaw0jVi_o',
    appId: '1:977548969242:web:5d8b752563638bcc3458a3',
    messagingSenderId: '977548969242',
    projectId: 'prakflutterfirebase-63b02',
    authDomain: 'prakflutterfirebase-63b02.firebaseapp.com',
    storageBucket: 'prakflutterfirebase-63b02.appspot.com',
    measurementId: 'G-K53T3C20JT',
  );
}
